### ISSUE TITLE
multi-level grouping and structured columns definition

### ISSUE THREAD

**Issue by keik** [keik/slickgrid-colgroup-plugin#2]
To get more flexibility, it is better to be able to accept structured columns definition, such like:

``` js
var columns = [
  {id: 'col 1', name: 'col 1', children: [
    {id: 'col 1-1', name: 'col 1-1', field: 'col1-1'},
    {id: 'col 1-2', name: 'col 1-2', field: 'col1-2'}
  ]},
  {id: 'col 2', name: 'col 2', children: [
    {id: 'col 2-1', name: 'col 2-1', field: 'col2-1'},
    {id: 'col 2-2', name: 'col 2-2', children: [
      {id: 'col 2-2-1', name: 'col 2-2-1', field: 'col2-2-1'},
      {id: 'col 2-2-2', name: 'col 2-2-2', field: 'col2-2-2'}
    ]}
  ]}
];
```

It would be rendered such like:

<table>
  <thead>
    <tr>
      <th colspan="2">col 1</th>
      <th colspan="3">col 2</th>      
    </tr>
    <tr>
      <th rowspan="2">col 1-1</th>
      <th rowspan="2">col 1-2</th>
      <th rowspan="2">col 2-1</th>
      <th colspan="2">col 2-2</th>
    </tr>
    <tr>
      <th>col 2-2-1</th>
      <th>col 2-2-2</th>      
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

**Comment by keik** [comment]
Created branch [structured-columns](https://github.com/keik/slickgrid-colgroup-plugin/tree/structured-columns)

**Comment by Alex--wu** [comment]
waiting this feature to release :) :+1:

**Comment by keik** [comment]
I cannot guarantee to release this feature but I think I try to restart implementation again!

**Comment by keik** [comment]
done fe9da4131365a24fbf5297578eeaf4701b238e9b
